export interface MedicineItem {
  id: string;
  barcode: string;
  name: string;
  activeIngredient: string;
  category: "Ağrı Kesici & Ateş Düşürücü" | "Antibiyotik" | "Mide Koruyucu & Antiasit" | "Alerji & Antihistaminik" | "Kalp & Tansiyon" | "Diyabet & İnsülin" | "Vitamin & Mineral" | "Solunum & Astım" | "Göz & Kulak Damlası";
  prescriptionType: "Reçetesiz (OTC - Serbest)" | "Reçeteli (Normal)" | "Kırmızı Reçete (Narkotik)" | "Yeşil Reçete (Psikotrop)" | "Mor / Turuncu Reçete";
  isReimbursedBySGK: boolean;
  publicSalePrice: number; // KDV Dahil PSF (TL)
  publicBasePrice: number; // Kamu Taban Fiyatı (TL)
  patientCopayEstimated: number; // Emekli %10 / Çalışan %20 Katkı Payı
  manufacturer: string;
  indications: string;
  usageInstructions: string;
  prescriptionWarning: string;
}

export const MEDICINES_DATABASE: MedicineItem[] = [
  {
    id: "parol-500",
    barcode: "8699525010045",
    name: "Parol 500 mg Tablet (30 Tablet)",
    activeIngredient: "Parasetamol",
    category: "Ağrı Kesici & Ateş Düşürücü",
    prescriptionType: "Reçetesiz (OTC - Serbest)",
    isReimbursedBySGK: true,
    publicSalePrice: 48.50,
    publicBasePrice: 42.00,
    patientCopayEstimated: 4.85,
    manufacturer: "Atabay İlaç",
    indications: "Hafif ve orta dereceli baş, kas, diş ağrıları ve ateşli hastalıklarda ilk basamak tedavidir.",
    usageInstructions: "Günde 1-3 defa, 4-6 saat aralıklarla 1 tablet bol su ile içilir. Aç veya tok alınabilir.",
    prescriptionWarning: "Reçetesiz serbestçe eczanelerden temin edilebilir. Alkolle birlikte kesinlikle tüketilmemelidir.",
  },
  {
    id: "arveles-25",
    barcode: "8699536090128",
    name: "Arveles 25 mg Film Tablet (20 Tablet)",
    activeIngredient: "Deksketoprofen Trometamol",
    category: "Ağrı Kesici & Ateş Düşürücü",
    prescriptionType: "Reçeteli (Normal)",
    isReimbursedBySGK: true,
    publicSalePrice: 76.80,
    publicBasePrice: 68.50,
    patientCopayEstimated: 7.68,
    manufacturer: "Menarini İlaç",
    indications: "Akut kas-iskelet sistemi ağrıları, diş ağrısı ve şiddetli adet sancılarında hızlı rahatlama sağlar.",
    usageInstructions: "Yemeklerden 30 dakika önce (aç karnına) 1 tablet alınırsa 15 dakikada çok hızlı etki eder.",
    prescriptionWarning: "Mide ülseri ve böbrek yetmezliği hastalarında doktor kontrolünde reçete ile alınmalıdır.",
  },
  {
    id: "majezik-100",
    barcode: "8699514091574",
    name: "Majezik 100 mg Film Tablet (15 Tablet)",
    activeIngredient: "Flurbiprofen",
    category: "Ağrı Kesici & Ateş Düşürücü",
    prescriptionType: "Reçeteli (Normal)",
    isReimbursedBySGK: true,
    publicSalePrice: 84.20,
    publicBasePrice: 75.00,
    patientCopayEstimated: 8.42,
    manufacturer: "Sanovel İlaç",
    indications: "Romatoid artrit, osteoartrit, boğaz iltihabı ve diş çekimi sonrası operasyonel ağrılar.",
    usageInstructions: "Günde 1 veya 2 tablet mutlaka yemeklerden sonra tok karnına bol su ile yutulmalıdır.",
    prescriptionWarning: "Aç karnına alınması mide kanaması riskini artırabilir; doktor reçetesiyle kullanılmalıdır.",
  },
  {
    id: "apranax-fort-550",
    barcode: "8699508090288",
    name: "Apranax Fort 550 mg Film Tablet (20 Tablet)",
    activeIngredient: "Naproksen Sodyum",
    category: "Ağrı Kesici & Ateş Düşürücü",
    prescriptionType: "Reçeteli (Normal)",
    isReimbursedBySGK: true,
    publicSalePrice: 104.50,
    publicBasePrice: 92.00,
    patientCopayEstimated: 10.45,
    manufacturer: "Abdi İbrahim",
    indications: "Migren atakları, şiddetli bel/boyun tutulması, diş cerrahisi ve ortopedik operasyon ağrıları.",
    usageInstructions: "Günde en fazla 2 tablet; yemekten hemen sonra bir tam bardak su ile alınmalıdır (etkisi 12 saat sürer).",
    prescriptionWarning: "Uzun etkili güçlü bir NSAİİ'dir. Reçetesiz kontrolsüz kullanılmamalıdır.",
  },
  {
    id: "augmentin-1000",
    barcode: "8699522095632",
    name: "Augmentin-BID 1000 mg Film Tablet (14 Tablet)",
    activeIngredient: "Amoksisilin + Klavulanik Asit",
    category: "Antibiyotik",
    prescriptionType: "Reçeteli (Normal)",
    isReimbursedBySGK: true,
    publicSalePrice: 142.30,
    publicBasePrice: 128.00,
    patientCopayEstimated: 14.23,
    manufacturer: "GlaxoSmithKline",
    indications: "Bakteriyel sinüzit, orta kulak iltihabı, bademcik iltihabı, zatürre ve idrar yolu enfeksiyonları.",
    usageInstructions: "12 saatte bir (sabah-akşam aynı saatte) yemek başlangıcında alınmalıdır.",
    prescriptionWarning: "YASAL ZORUNLULUK: Antibiyotikler reçetesiz kesinlikle satılamaz. Grip/nezlede etkisizdir.",
  },
  {
    id: "lansor-30",
    barcode: "8699514151247",
    name: "Lansor 30 mg Mikropellet Kapsül (28 Kapsül)",
    activeIngredient: "Lansoprazol",
    category: "Mide Koruyucu & Antiasit",
    prescriptionType: "Reçeteli (Normal)",
    isReimbursedBySGK: true,
    publicSalePrice: 118.00,
    publicBasePrice: 105.00,
    patientCopayEstimated: 11.80,
    manufacturer: "Sanovel İlaç",
    indications: "Mide ve onikiparmak bağırsağı ülseri, gastroözofageal reflü ve NSAİİ ilişkili mide hasarını önleme.",
    usageInstructions: "Sabahları kahvaltıdan en az 30-45 dakika önce aç karnına bir bardak su ile yutulmalıdır.",
    prescriptionWarning: "Kronik mide şikayetlerinde hekim teşhisi ve endoskopi takibiyle reçetelendirilir.",
  },
  {
    id: "gaviscon-surup",
    barcode: "8699546570023",
    name: "Gaviscon Likit Süspansiyon (200 ml Şurup)",
    activeIngredient: "Sodyum Aljinat + Sodyum Bikarbonat",
    category: "Mide Koruyucu & Antiasit",
    prescriptionType: "Reçetesiz (OTC - Serbest)",
    isReimbursedBySGK: true,
    publicSalePrice: 92.40,
    publicBasePrice: 84.00,
    patientCopayEstimated: 9.24,
    manufacturer: "Reckitt Benckiser",
    indications: "Mide ekşimesi, asit reflüsü ve yemek sonrası göğüste yanma hissinde koruyucu bariyer oluşturur.",
    usageInstructions: "Yemeklerden sonra ve yatarken 10-20 ml (2-4 tatlı kaşığı) içilir.",
    prescriptionWarning: "Reçetesiz serbestçe temin edilebilir. Şişe açıldıktan sonra 6 ay içinde tüketilmelidir.",
  },
  {
    id: "zyrtec-10",
    barcode: "8699559090037",
    name: "Zyrtec 10 mg Film Tablet (20 Tablet)",
    activeIngredient: "Setirizin Dihidroklorür",
    category: "Alerji & Antihistaminik",
    prescriptionType: "Reçetesiz (OTC - Serbest)",
    isReimbursedBySGK: true,
    publicSalePrice: 88.60,
    publicBasePrice: 79.00,
    patientCopayEstimated: 8.86,
    manufacturer: "UCB Pharma",
    indications: "Mevsimsel alerjik rinit (bahar nezlesi), göz sulanması, kaşıntı ve kurdeşen (ürtiker).",
    usageInstructions: "Günde 1 defa tercihen akşamları yatmadan önce 1 tablet alınır.",
    prescriptionWarning: "Hafif uyku ve konsantrasyon kaybı yapabileceğinden araç kullanırken dikkat edilmelidir.",
  },
  {
    id: "beloc-zok-50",
    barcode: "8699786090091",
    name: "Beloc ZOK 50 mg Kontrollü Salımlı Tablet (20 Tablet)",
    activeIngredient: "Metoprolol Süksinat",
    category: "Kalp & Tansiyon",
    prescriptionType: "Reçeteli (Normal)",
    isReimbursedBySGK: true,
    publicSalePrice: 96.70,
    publicBasePrice: 87.00,
    patientCopayEstimated: 9.67,
    manufacturer: "AstraZeneca",
    indications: "Hipertansiyon, kalp çarpıntısı, anjina pektoris ve kalp yetmezliği tedavisi.",
    usageInstructions: "Günde 1 defa sabahları çiğnenmeden su ile alınmalıdır. İlaç aniden kesilmemelidir.",
    prescriptionWarning: "Kardiyoloji uzmanı takibinde raporlu/reçeteli kullanılır. Asla kendi kendine bırakılamaz.",
  },
  {
    id: "glifor-1000",
    barcode: "8699525095325",
    name: "Glifor 1000 mg Film Tablet (100 Tablet)",
    activeIngredient: "Metformin Hidroklorür",
    category: "Diyabet & İnsülin",
    prescriptionType: "Reçeteli (Normal)",
    isReimbursedBySGK: true,
    publicSalePrice: 135.00,
    publicBasePrice: 122.00,
    patientCopayEstimated: 13.50,
    manufacturer: "Bilim İlaç",
    indications: "Tip 2 diyabet (şeker hastalığı) kan şekeri kontrolü ve insülin direnci tedavisi.",
    usageInstructions: "Yemeklerle birlikte veya yemekten hemen sonra alınır (mide bulantısını önlemek için).",
    prescriptionWarning: "Düzenli HbA1c ve böbrek fonksiyon testleri gerektiren reçeteli bir ilaçtır.",
  },
  {
    id: "devit-3-damla",
    barcode: "8699508590054",
    name: "Devit-3 Oral Damla (15 ml)",
    activeIngredient: "Kolekalsiferol (D3 Vitamini 50.000 IU)",
    category: "Vitamin & Mineral",
    prescriptionType: "Reçetesiz (OTC - Serbest)",
    isReimbursedBySGK: true,
    publicSalePrice: 62.50,
    publicBasePrice: 55.00,
    patientCopayEstimated: 6.25,
    manufacturer: "Deva Holding",
    indications: "D vitamini eksikliği, osteoporoz destek tedavisi ve kemik sağlığı.",
    usageInstructions: "Doktorun önerdiği damla sayısı kadar ekmek veya kaşığa damlatılarak yağlı gıdayla tüketilir.",
    prescriptionWarning: "Aşırı doz hiperkalsemiye yol açabileceğinden kan D vitamini düzeyine göre kullanılmalıdır.",
  },
  {
    id: "ventolin-inhaler",
    barcode: "8699522522510",
    name: "Ventolin Evohaler İnhalasyon Aerosolü (200 Doz)",
    activeIngredient: "Salbutamol",
    category: "Solunum & Astım",
    prescriptionType: "Reçeteli (Normal)",
    isReimbursedBySGK: true,
    publicSalePrice: 112.80,
    publicBasePrice: 101.00,
    patientCopayEstimated: 11.28,
    manufacturer: "GlaxoSmithKline",
    indications: "Astım krizleri, KOAH alevlenmeleri ve nefes darlığında hava yollarını hızla açar.",
    usageInstructions: "Nefes darlığı atağı sırasında ağızdan 1-2 puf derin nefes alınarak uygulanır.",
    prescriptionWarning: "Acil kurtarıcı ilaçtır; göğüs hastalıkları hekiminin reçetesiyle temin edilir.",
  },
  {
    id: "tobised-goz-damlasi",
    barcode: "8699540610114",
    name: "Tobrex / Tobised %0.3 Göz Damlası (5 ml)",
    activeIngredient: "Tobramisin",
    category: "Göz & Kulak Damlası",
    prescriptionType: "Reçeteli (Normal)",
    isReimbursedBySGK: true,
    publicSalePrice: 78.40,
    publicBasePrice: 70.00,
    patientCopayEstimated: 7.84,
    manufacturer: "Novartis / Bilim İlaç",
    indications: "Bakteriyel konjonktivit (göz iltihabı), çapaklanma ve göz kapağı enfeksiyonları.",
    usageInstructions: "Günde 3-4 defa enfekte göze 1'er damla damlatılır. Şişe ucu göze değdirilmemelidir.",
    prescriptionWarning: "Şişe açıldıktan sonra maksimum 15-30 gün içinde tüketilmelidir, aksi halde bakteri ürer.",
  },
];
